#!/bin/bash
ln -siT $HOME/dotfiles/.vim $HOME/.vim
ln -si $HOME/dotfiles/.vimrc $HOME/.vimrc
ln -si $HOME/dotfiles/.bashrc $HOME/.bashrc
ln -si $HOME/dotfiles/.bash_profile $HOME/.bash_profile
ln -si $HOME/dotfiles/.tmux.conf $HOME/.tmux.conf
ln -si $HOME/dotfiles/.inputrc $HOME/.inputrc
